apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: {{ include "velero.backupStorageLocation.name" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "velero.labels" . | nindent 4 }}
spec:
  provider: {{ include "velero.backupStorageLocation.provider" . }}
  {{- with .Values.configuration.backupStorageLocation.default }}
  default: {{ . }}
  {{- end }}
  {{- with .Values.configuration.backupStorageLocation }}
  objectStorage:
    bucket: dc15-cmf-prd-c1
    prefix: dc15-cmf-prd-bkups
    {{- end }}