apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "velero.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
     {{- include "velero.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
